document.write('<!-- to hide button on small screens, add w3-hide-small -->');
document.write('<div class="w3-top" style="color: #ffcc0081;">');
document.write('    <div class="w3-bar w3-black w3-card">');
document.write('        <a href="index.html" class="w3-bar-item w3-button w3-padding-large w3-hide-small w3-hide-medium">');
document.write('            <img src="img/logotrasp.png" style="height:25px; margin-bottom: 0px; margin-top: -4px">');
document.write('            HOME</a>');
document.write('        <a href="chisiamo.html" class="w3-bar-item w3-button w3-padding-large w3-hide-small w3-hide-medium">CHI SIAMO</a>');
document.write('        <a href="rappresentanza.html" class="w3-bar-item w3-button w3-padding-large w3-hide-small w3-hide-medium">RAPPRESENTANZA</a>');
document.write('        <a href="linkutili.html" class="w3-bar-item w3-button w3-padding-large w3-hide-small w3-hide-medium">LINK UTILI</a>');
document.write('        <a href="contatti.html" class="w3-bar-item w3-button w3-padding-large w3-hide-small w3-hide-medium">CONTATTI</a>');
document.write('');
document.write('        <div class="w3-dropdown-hover w3-hide-large ">');
document.write('            <button class="w3-padding-large w3-button" title="More">&#9776 <i class="fa fa-caret-down"></i></button>');
document.write('            <div class="w3-dropdown-content w3-bar-block w3-card-4"> <!-- onclick="myFunction()"> -->');
document.write('                <a href="index.html" class="w3-bar-item w3-button">HOME</a>');
document.write('                <a href="chisiamo.html" class="w3-bar-item w3-button">CHI SIAMO</a>');
document.write('                <a href="rappresentanza.html" class="w3-bar-item w3-button ">RAPPRESENTANZA</a>');
document.write('                <a href="linkutili.html" class="w3-bar-item w3-button">LINK UTILI</a>');
document.write('                <a href="contatti.html" class="w3-bar-item w3-button">CONTATTI</a>');
document.write('            </div>');
document.write('        </div>');
document.write('');
document.write('        <div class="w3-dropdown-hover">');
document.write('            <button class="w3-padding-large w3-button" title="More">SPORTELLO STUDENTI <i');
document.write('                    class="fa fa-caret-down"></i></button>');
document.write('            <div class="w3-dropdown-content w3-bar-block w3-card-4">');
document.write('                <a href="sportello.html" class="w3-bar-item w3-button">Cos\'è lo sportello?</a>');
document.write('                <a href="anno1.html" class="w3-bar-item w3-button">Primo anno</a>');
document.write('                <a href="anno2.html" class="w3-bar-item w3-button">Secondo anno</a>');
document.write('                <a href="anno3.html" class="w3-bar-item w3-button">Terzo anno</a>');
document.write('                <a href="magistrale.html" class="w3-bar-item w3-button">Magistrale</a>');
document.write('            </div>');
document.write('        </div>');
document.write('    </div>');
document.write('</div>');
