document.write('<!-- to hide button on small screens, add w3-hide-small -->');
document.write('<div class="w3-top" style="color: #ffcc0081;">');
document.write('    <div class="w3-bar w3-black w3-card">');
document.write('        <a href="index.html" class="w3-bar-item w3-button w3-padding-large w3-hide-small w3-hide-medium">');
document.write('            <img src="img/logotrasp.png" style="height:25px; margin-bottom: 0px; margin-top: -4px">');
document.write('            HOME</a>');
document.write('        <a href="chisiamo.html" class="w3-bar-item w3-button w3-padding-large w3-hide-small w3-hide-medium">CHI SIAMO</a>');
document.write('        <a href="storia.html" class="w3-bar-item w3-button w3-padding-large w3-hide-small w3-hide-medium">STORIA</a>');
document.write('        <a href="linkutili.html" class="w3-bar-item w3-button w3-padding-large w3-hide-small w3-hide-medium">LINK UTILI E CURIOSITA`</a>');
document.write('        <a href="feste.html" class="w3-bar-item w3-button w3-padding-large w3-hide-small w3-hide-medium">FESTE IN CASCINA</a>');
document.write('        <a href="comearrivare.html" class="w3-bar-item w3-button w3-padding-large w3-hide-small w3-hide-medium">COME ARRIVARE</a>');
document.write('');
document.write('        <div class="w3-dropdown-hover w3-hide-large ">');
document.write('            <button class="w3-padding-large w3-button" title="More">&#9776 <i class="fa fa-caret-down"></i></button>');
document.write('            <div class="w3-dropdown-content w3-bar-block w3-card-4"> <!-- onclick="myFunction()"> -->');
document.write('                <a href="index.html" class="w3-bar-item w3-button">HOME</a>');
document.write('                <a href="chisiamo.html" class="w3-bar-item w3-button">CHI SIAMO</a>');
document.write('                <a href="storia.html" class="w3-bar-item w3-button ">STORIA</a>');
document.write('                <a href="linkutili.html" class="w3-bar-item w3-button">LINK UTILI E CURIOSITA`</a>');
document.write('                <a href="feste.html" class="w3-bar-item w3-button">FESTE IN CASCINA</a>');
document.write('                <a href="comearrivare.html" class="w3-bar-item w3-button">COME ARRIVARE</a>');
document.write('            </div>');
document.write('        </div>');
document.write('    </div>');
document.write('</div>');
